// ABI fragments for dashboard interaction with deployed contracts
// Full ABIs are auto-generated by Hardhat in artifacts/

export const CPE_ABI = [
  "function createTask(uint256,uint8,bytes32,uint256,uint256) returns (uint256)",
  "function getTask(uint256) view returns (tuple(address payer, address payee, uint256 amount, bytes32 conditionHash, tuple(uint8 conditionType, bytes32 fieldName, uint256 threshold) condition, uint256 deadline, uint8 status, bytes32 outputHash, string resultUri))",
  "function getOpenTasks() view returns (uint256[])",
  "function taskCount() view returns (uint256)",
  "function claimExpired(uint256)",
  "event TaskCreated(uint256 indexed taskId, address indexed payer, uint256 amount, bytes32 conditionHash, uint256 deadline)",
  "event TaskAccepted(uint256 indexed taskId, address indexed payee)",
  "event DeliverySubmitted(uint256 indexed taskId, address indexed agent, bytes32 outputHash, string resultUri)",
  "event TaskSettled(uint256 indexed taskId, bool passed, address recipient, uint256 amount)"
];

export const ERC8004_ABI = [
  "function getAgent(address) view returns (uint256 trustScore, bytes32[] capabilities, bool registered)",
  "event AgentRegistered(address indexed agent, uint256 initialScore)",
  "event ReputationUpdated(address indexed agent, bool passed, uint256 newScore)"
];

export const USDC_ABI = [
  "function approve(address,uint256) returns (bool)",
  "function allowance(address,address) view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function decimals() view returns (uint8)"
];

// Contract addresses — loaded from env vars
export const CONTRACTS = {
  cpe:     process.env.NEXT_PUBLIC_CPE_ADDRESS     || "",
  erc8004: process.env.NEXT_PUBLIC_ERC8004_ADDRESS || "",
  usdc:    process.env.NEXT_PUBLIC_USDC_ADDRESS    || "0x5425890298aed601595a70AB815c96711a31Bc65",
};

export const SNOWTRACE_BASE = process.env.NEXT_PUBLIC_SNOWTRACE_BASE || "https://testnet.snowtrace.io";

// Avalanche Fuji chain config for MetaMask
export const FUJI_CHAIN = {
  chainId: "0xA869", // 43113 in hex
  chainName: "Avalanche Fuji C-Chain",
  nativeCurrency: { name: "AVAX", symbol: "AVAX", decimals: 18 },
  rpcUrls: [process.env.NEXT_PUBLIC_FUJI_RPC || "https://api.avax-test.network/ext/bc/C/rpc"],
  blockExplorerUrls: ["https://testnet.snowtrace.io"],
};

// Condition type labels
export const CONDITION_LABELS = {
  0: "FORMAT_JSON",
  1: "FIELD_EXISTS",
  2: "VALUE_THRESHOLD",
};

// Task status labels + colors
export const STATUS_CONFIG = {
  0: { label: "LOCKED",        color: "#f59e0b", bg: "rgba(245,158,11,0.15)" },
  1: { label: "PENDING_PROOF", color: "#3b82f6", bg: "rgba(59,130,246,0.15)" },
  2: { label: "SETTLED_PASS",  color: "#10b981", bg: "rgba(16,185,129,0.15)" },
  3: { label: "SETTLED_FAIL",  color: "#ef4444", bg: "rgba(239,68,68,0.15)" },
};
